# Generated by Django 2.2.2 on 2019-07-23 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_profile_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_of_birth',
        ),
    ]
